version: '3.7'

volumes:
  prometheus_data: { }
  grafana_data: { }

networks:
  smart-city:

services:

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: smart-city-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    networks:
      - smart-city

  # Grafana
  grafana:
    image: grafana/grafana-oss:9.2.0
    container_name: smart-city-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    env_file:
      - ./grafana/config
    networks:
      - smart-city

  #  Smart Mobility
  smart-mobility:
    build:
      context: ../smartmobility
      dockerfile: Dockerfile
    container_name: smart-city-smart-mobility
    image: smart-city/smart-mobility
    restart: unless-stopped
    depends_on:
      - payment
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: default
    healthcheck:
      test: "exit 0"
    networks:
      - smart-city

  #  Payment
  payment:
    build:
      context: ../payment
      dockerfile: Dockerfile
    container_name: smart-city-payment
    image: smart-city/payment
    restart: unless-stopped
    ports:
      - "8091:8091"
    environment:
      SPRING_PROFILES_ACTIVE: default
    healthcheck:
      test: "exit 0"
    networks:
      - smart-city