### creates reservation
POST localhost:8090/reservations
Content-Type: application/json

{
  "userId": 1,
  "autonomousCarId": 1
}

### cretes random reservation
POST localhost:8090/reservations/random
Content-Type: application/json


### confirms reservation
PUT localhost:8090/reservations
Content-Type: application/json

{
  "reservationBusinessKey": "02f4c1fc-30d5-48a7-8c6d-468d30761b2e",
  "price": 22.4
}

### cancels reservation
DELETE localhost:8090/reservations
Content-Type: application/json

{
  "reservationBusinessKey": "02f4c1fc-30d5-48a7-8c6d-468d30761b2e"
}

### creates payment
POST localhost:8091/payments
Content-Type: application/json

{
  "reservationExternalBusinessKey": "02f4c1fc-30d5-48a7-8c6d-468d30761b2e"
}